version: 2.1

jobs:
  build:
    docker:
      - image: floydpink/ubuntu-install-builder:23.11.0
    steps:
      - checkout
      - run: sudo apt-get --allow-releaseinfo-change update
      - run: sudo apt-get install wget rpm -y
      - run: sudo cert-sync /etc/ssl/certs/ca-certificates.crt
      - run: echo -e "y\n" | sudo certmgr -ssl -m https://go.microsoft.com
      - run: echo -e "y\n" | sudo certmgr -ssl -m https://nugetgallery.blob.core.windows.net
      - run: echo -e "y\n" | sudo certmgr -ssl -m https://nuget.org
      - run: cd build-tools && ./go.sh circleci Release

workflows:
  ci_cd:
    jobs:
      - build:
          filters:
            tags:
              ignore: /.*/
            branches:
              only: main

# VS Code Extension Version: 1.5.0
