
// This file has been generated by the GUI designer. Do not modify.
namespace FloydPink.Flickr.Downloadr
{
	public partial class LoginWindow
	{
		private global::Gtk.VBox LoggedOutCanvas;
		private global::Gtk.VBox vbox3;
		private global::Gtk.Alignment alignment3;
		private global::Gtk.Image image3;
		private global::Gtk.Alignment alignment2;
		private global::Gtk.VBox vbox5;
		private global::Gtk.Label label1;
		private global::Gtk.VBox vbox2;
		private global::Gtk.HBox hbox5;
		private global::Gtk.Fixed fixed2;
		private global::Gtk.Button buttonLogin;
		private global::Gtk.Fixed fixed1;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget FloydPink.Flickr.Downloadr.LoginWindow
			this.Name = "FloydPink.Flickr.Downloadr.LoginWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("Welcome - flickr downloadr");
			this.Icon = global::Gdk.Pixbuf.LoadFromResource ("FloydPink.Flickr.Downloadr.icon.png");
			this.WindowPosition = ((global::Gtk.WindowPosition)(3));
			this.DefaultWidth = 495;
			this.DefaultHeight = 287;
			// Container child FloydPink.Flickr.Downloadr.LoginWindow.Gtk.Container+ContainerChild
			this.LoggedOutCanvas = new global::Gtk.VBox ();
			this.LoggedOutCanvas.Name = "LoggedOutCanvas";
			this.LoggedOutCanvas.Spacing = 6;
			// Container child LoggedOutCanvas.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.alignment3 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment3.Name = "alignment3";
			this.vbox3.Add (this.alignment3);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.alignment3]));
			w1.Position = 0;
			// Container child vbox3.Gtk.Box+BoxChild
			this.image3 = new global::Gtk.Image ();
			this.image3.WidthRequest = 330;
			this.image3.HeightRequest = 79;
			this.image3.Name = "image3";
			this.image3.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("FloydPink.Flickr.Downloadr.logo-Small.png");
			this.vbox3.Add (this.image3);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.image3]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.alignment2 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment2.Name = "alignment2";
			this.vbox3.Add (this.alignment2);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.alignment2]));
			w3.Position = 2;
			this.LoggedOutCanvas.Add (this.vbox3);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.LoggedOutCanvas [this.vbox3]));
			w4.Position = 0;
			w4.Expand = false;
			// Container child LoggedOutCanvas.Gtk.Box+BoxChild
			this.vbox5 = new global::Gtk.VBox ();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Welcome to Flickr Downloadr. Click 'Login' to continue.");
			this.vbox5.Add (this.label1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.label1]));
			w5.Position = 2;
			w5.Expand = false;
			w5.Fill = false;
			this.LoggedOutCanvas.Add (this.vbox5);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.LoggedOutCanvas [this.vbox5]));
			w6.Position = 1;
			// Container child LoggedOutCanvas.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox ();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.fixed2 = new global::Gtk.Fixed ();
			this.fixed2.Name = "fixed2";
			this.fixed2.HasWindow = false;
			this.hbox5.Add (this.fixed2);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.fixed2]));
			w7.Position = 0;
			// Container child hbox5.Gtk.Box+BoxChild
			this.buttonLogin = new global::Gtk.Button ();
			this.buttonLogin.WidthRequest = 141;
			this.buttonLogin.HeightRequest = 31;
			this.buttonLogin.CanFocus = true;
			this.buttonLogin.Name = "buttonLogin";
			this.buttonLogin.UseUnderline = true;
			this.buttonLogin.Label = global::Mono.Unix.Catalog.GetString ("Login");
			this.hbox5.Add (this.buttonLogin);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.buttonLogin]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.fixed1 = new global::Gtk.Fixed ();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			this.hbox5.Add (this.fixed1);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.fixed1]));
			w9.Position = 2;
			this.vbox2.Add (this.hbox5);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox5]));
			w10.Position = 1;
			w10.Expand = false;
			w10.Fill = false;
			this.LoggedOutCanvas.Add (this.vbox2);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.LoggedOutCanvas [this.vbox2]));
			w11.Position = 2;
			this.Add (this.LoggedOutCanvas);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Show ();
			this.buttonLogin.Clicked += new global::System.EventHandler (this.buttonLoginClick);
		}
	}
}
