
// This file has been generated by the GUI designer. Do not modify.
namespace FloydPink.Flickr.Downloadr
{
	public partial class CachedImageWidget
	{
		private global::Gtk.Image imageMain;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget FloydPink.Flickr.Downloadr.CachedImageWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "FloydPink.Flickr.Downloadr.CachedImageWidget";
			// Container child FloydPink.Flickr.Downloadr.CachedImageWidget.Gtk.Container+ContainerChild
			this.imageMain = new global::Gtk.Image ();
			this.imageMain.Name = "imageMain";
			this.Add (this.imageMain);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
