
// This file has been generated by the GUI designer. Do not modify.
namespace FloydPink.Flickr.Downloadr.UI.Widgets
{
	public partial class SpinnerWidget
	{
		private global::Gtk.VBox vboxRoot;
		private global::Gtk.HBox hboxSpinner;
		private global::Gtk.Alignment alignment12;
		private global::Gtk.Image imageLoading;
		private global::Gtk.Label labelOperation;
		private global::Gtk.Alignment alignment11;
		private global::Gtk.HBox hboxPercent;
		private global::Gtk.Alignment alignment6;
		private global::Gtk.Label labelPercent;
		private global::Gtk.VBox vbox8;
		private global::Gtk.Button buttonCancel;
		private global::Gtk.Alignment alignment5;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget FloydPink.Flickr.Downloadr.UI.Widgets.SpinnerWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "FloydPink.Flickr.Downloadr.UI.Widgets.SpinnerWidget";
			// Container child FloydPink.Flickr.Downloadr.UI.Widgets.SpinnerWidget.Gtk.Container+ContainerChild
			this.vboxRoot = new global::Gtk.VBox ();
			this.vboxRoot.Name = "vboxRoot";
			this.vboxRoot.Spacing = 6;
			// Container child vboxRoot.Gtk.Box+BoxChild
			this.hboxSpinner = new global::Gtk.HBox ();
			this.hboxSpinner.Name = "hboxSpinner";
			this.hboxSpinner.Spacing = 6;
			// Container child hboxSpinner.Gtk.Box+BoxChild
			this.alignment12 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment12.Name = "alignment12";
			this.hboxSpinner.Add (this.alignment12);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hboxSpinner [this.alignment12]));
			w1.Position = 0;
			// Container child hboxSpinner.Gtk.Box+BoxChild
			this.imageLoading = new global::Gtk.Image ();
			this.imageLoading.Name = "imageLoading";
			this.hboxSpinner.Add (this.imageLoading);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hboxSpinner [this.imageLoading]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hboxSpinner.Gtk.Box+BoxChild
			this.labelOperation = new global::Gtk.Label ();
			this.labelOperation.Name = "labelOperation";
			this.labelOperation.Xalign = 0F;
			this.labelOperation.LabelProp = global::Mono.Unix.Catalog.GetString ("Please wait...");
			this.hboxSpinner.Add (this.labelOperation);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hboxSpinner [this.labelOperation]));
			w3.Position = 2;
			w3.Expand = false;
			// Container child hboxSpinner.Gtk.Box+BoxChild
			this.alignment11 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment11.Name = "alignment11";
			this.hboxSpinner.Add (this.alignment11);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hboxSpinner [this.alignment11]));
			w4.Position = 3;
			this.vboxRoot.Add (this.hboxSpinner);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vboxRoot [this.hboxSpinner]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vboxRoot.Gtk.Box+BoxChild
			this.hboxPercent = new global::Gtk.HBox ();
			this.hboxPercent.Name = "hboxPercent";
			this.hboxPercent.Spacing = 6;
			// Container child hboxPercent.Gtk.Box+BoxChild
			this.alignment6 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment6.Name = "alignment6";
			this.hboxPercent.Add (this.alignment6);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hboxPercent [this.alignment6]));
			w6.Position = 0;
			// Container child hboxPercent.Gtk.Box+BoxChild
			this.labelPercent = new global::Gtk.Label ();
			this.labelPercent.Name = "labelPercent";
			this.labelPercent.LabelProp = global::Mono.Unix.Catalog.GetString ("Percent Done");
			this.hboxPercent.Add (this.labelPercent);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hboxPercent [this.labelPercent]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			// Container child hboxPercent.Gtk.Box+BoxChild
			this.vbox8 = new global::Gtk.VBox ();
			this.vbox8.Name = "vbox8";
			this.vbox8.Spacing = 6;
			// Container child vbox8.Gtk.Box+BoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = global::Mono.Unix.Catalog.GetString ("Cancel");
			this.vbox8.Add (this.buttonCancel);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.buttonCancel]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			this.hboxPercent.Add (this.vbox8);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hboxPercent [this.vbox8]));
			w9.Position = 2;
			w9.Expand = false;
			w9.Fill = false;
			// Container child hboxPercent.Gtk.Box+BoxChild
			this.alignment5 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment5.Name = "alignment5";
			this.hboxPercent.Add (this.alignment5);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hboxPercent [this.alignment5]));
			w10.Position = 3;
			this.vboxRoot.Add (this.hboxPercent);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vboxRoot [this.hboxPercent]));
			w11.Position = 2;
			w11.Expand = false;
			w11.Fill = false;
			this.Add (this.vboxRoot);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.buttonCancel.Clicked += new global::System.EventHandler (this.buttonCancelClick);
		}
	}
}
