// This file has been generated by the GUI designer. Do not modify.
using Gdk;
using Gtk;
using Mono.Unix;
using Stetic;
using Image = Gtk.Image;

namespace FloydPink.Flickr.Downloadr {
    public partial class LoginWindow {
        private VBox LoggedOutCanvas;
        private Alignment alignment1;
        private Alignment alignment10;
        private Alignment alignment2;
        private Alignment alignment3;
        private Alignment alignment4;
        private Alignment alignment5;
        private Alignment alignment6;
        private Alignment alignment7;
        private Alignment alignment8;
        private Alignment alignment9;
        private Button buttonAbout;
        private Button buttonContinue;
        private Button buttonLogin;
        private Button buttonLogout;
        private Button buttonPrefs;
        private HBox hbox4;
        private HBox hbox8;
        private HBox hboxAvatar;
        private HBox hboxBottomButtons;
        private HBox hboxLogin;
        private Image image5;
        private Image imageBuddyIcon;
        private Label labelMessage;
        private Label labelWelcomeUsername;
        private VBox vbox1;
        private VBox vbox2;
        private VBox vbox3;
        private VBox vbox4;
        private VBox vbox5;
        private VBox vbox6;
        private VBox vbox7;

        protected virtual void Build() {
            Gui.Initialize(this);
            // Widget FloydPink.Flickr.Downloadr.LoginWindow
            WidthRequest = 495;
            HeightRequest = 287;
            Name = "FloydPink.Flickr.Downloadr.LoginWindow";
            Title = Catalog.GetString("Welcome - flickr downloadr");
            Icon = Pixbuf.LoadFromResource("FloydPink.Flickr.Downloadr.Assets.icon.png");
            WindowPosition = ((WindowPosition) (3));
            Resizable = false;
            AllowGrow = false;
            DefaultWidth = 495;
            DefaultHeight = 287;
            // Container child FloydPink.Flickr.Downloadr.LoginWindow.Gtk.Container+ContainerChild
            this.LoggedOutCanvas = new VBox();
            this.LoggedOutCanvas.Name = "LoggedOutCanvas";
            this.LoggedOutCanvas.Spacing = 6;
            // Container child LoggedOutCanvas.Gtk.Box+BoxChild
            this.vbox5 = new VBox();
            this.vbox5.Name = "vbox5";
            this.vbox5.Spacing = 6;
            // Container child vbox5.Gtk.Box+BoxChild
            this.vbox3 = new VBox();
            this.vbox3.Name = "vbox3";
            this.vbox3.Spacing = 6;
            this.vbox3.BorderWidth = 3;
            // Container child vbox3.Gtk.Box+BoxChild
            this.hbox8 = new HBox();
            this.hbox8.Name = "hbox8";
            this.hbox8.Spacing = 6;
            // Container child hbox8.Gtk.Box+BoxChild
            this.alignment8 = new Alignment(0.5F, 0.5F, 1F, 1F);
            this.alignment8.Name = "alignment8";
            this.hbox8.Add(this.alignment8);
            var w1 = ((Box.BoxChild) (this.hbox8[this.alignment8]));
            w1.Position = 0;
            // Container child hbox8.Gtk.Box+BoxChild
            this.image5 = new Image();
            this.image5.Name = "image5";
            this.image5.Pixbuf = Pixbuf.LoadFromResource("FloydPink.Flickr.Downloadr.Assets.logo-Small.png");
            this.hbox8.Add(this.image5);
            var w2 = ((Box.BoxChild) (this.hbox8[this.image5]));
            w2.Position = 1;
            w2.Expand = false;
            w2.Fill = false;
            // Container child hbox8.Gtk.Box+BoxChild
            this.vbox4 = new VBox();
            this.vbox4.Name = "vbox4";
            this.vbox4.Spacing = 6;
            // Container child vbox4.Gtk.Box+BoxChild
            this.buttonAbout = new Button();
            this.buttonAbout.WidthRequest = 65;
            this.buttonAbout.HeightRequest = 35;
            this.buttonAbout.CanFocus = true;
            this.buttonAbout.Name = "buttonAbout";
            this.buttonAbout.UseUnderline = true;
            this.buttonAbout.Label = Catalog.GetString("About");
            this.vbox4.Add(this.buttonAbout);
            var w3 = ((Box.BoxChild) (this.vbox4[this.buttonAbout]));
            w3.Position = 0;
            w3.Expand = false;
            w3.Fill = false;
            w3.Padding = 5;
            this.hbox8.Add(this.vbox4);
            var w4 = ((Box.BoxChild) (this.hbox8[this.vbox4]));
            w4.Position = 2;
            w4.Expand = false;
            w4.Fill = false;
            this.vbox3.Add(this.hbox8);
            var w5 = ((Box.BoxChild) (this.vbox3[this.hbox8]));
            w5.Position = 0;
            w5.Expand = false;
            w5.Fill = false;
            this.vbox5.Add(this.vbox3);
            var w6 = ((Box.BoxChild) (this.vbox5[this.vbox3]));
            w6.Position = 0;
            w6.Expand = false;
            w6.Fill = false;
            // Container child vbox5.Gtk.Box+BoxChild
            this.vbox6 = new VBox();
            this.vbox6.Name = "vbox6";
            this.vbox6.Spacing = 6;
            // Container child vbox6.Gtk.Box+BoxChild
            this.alignment6 = new Alignment(0.5F, 0.5F, 1F, 1F);
            this.alignment6.Name = "alignment6";
            this.vbox6.Add(this.alignment6);
            var w7 = ((Box.BoxChild) (this.vbox6[this.alignment6]));
            w7.Position = 0;
            // Container child vbox6.Gtk.Box+BoxChild
            this.hboxAvatar = new HBox();
            this.hboxAvatar.Name = "hboxAvatar";
            this.hboxAvatar.Spacing = 6;
            // Container child hboxAvatar.Gtk.Box+BoxChild
            this.alignment1 = new Alignment(0.5F, 0.5F, 1F, 1F);
            this.alignment1.Name = "alignment1";
            this.hboxAvatar.Add(this.alignment1);
            var w8 = ((Box.BoxChild) (this.hboxAvatar[this.alignment1]));
            w8.Position = 0;
            // Container child hboxAvatar.Gtk.Box+BoxChild
            this.hbox4 = new HBox();
            this.hbox4.Name = "hbox4";
            this.hbox4.Spacing = 6;
            // Container child hbox4.Gtk.Box+BoxChild
            this.imageBuddyIcon = new Image();
            this.imageBuddyIcon.Name = "imageBuddyIcon";
            this.hbox4.Add(this.imageBuddyIcon);
            var w9 = ((Box.BoxChild) (this.hbox4[this.imageBuddyIcon]));
            w9.Position = 0;
            w9.Expand = false;
            w9.Fill = false;
            // Container child hbox4.Gtk.Box+BoxChild
            this.vbox1 = new VBox();
            this.vbox1.Name = "vbox1";
            this.vbox1.Spacing = 6;
            // Container child vbox1.Gtk.Box+BoxChild
            this.alignment10 = new Alignment(0.5F, 0.5F, 1F, 1F);
            this.alignment10.Name = "alignment10";
            this.vbox1.Add(this.alignment10);
            var w10 = ((Box.BoxChild) (this.vbox1[this.alignment10]));
            w10.Position = 0;
            // Container child vbox1.Gtk.Box+BoxChild
            this.labelWelcomeUsername = new Label();
            this.labelWelcomeUsername.Name = "labelWelcomeUsername";
            this.labelWelcomeUsername.LabelProp = Catalog.GetString("Welcome, username!");
            this.labelWelcomeUsername.UseMarkup = true;
            this.vbox1.Add(this.labelWelcomeUsername);
            var w11 = ((Box.BoxChild) (this.vbox1[this.labelWelcomeUsername]));
            w11.Position = 1;
            w11.Expand = false;
            w11.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.alignment7 = new Alignment(0.5F, 0.5F, 1F, 1F);
            this.alignment7.Name = "alignment7";
            this.vbox1.Add(this.alignment7);
            var w12 = ((Box.BoxChild) (this.vbox1[this.alignment7]));
            w12.Position = 2;
            this.hbox4.Add(this.vbox1);
            var w13 = ((Box.BoxChild) (this.hbox4[this.vbox1]));
            w13.Position = 1;
            w13.Expand = false;
            w13.Fill = false;
            this.hboxAvatar.Add(this.hbox4);
            var w14 = ((Box.BoxChild) (this.hboxAvatar[this.hbox4]));
            w14.Position = 1;
            w14.Expand = false;
            w14.Fill = false;
            // Container child hboxAvatar.Gtk.Box+BoxChild
            this.alignment2 = new Alignment(0.5F, 0.5F, 1F, 1F);
            this.alignment2.Name = "alignment2";
            this.hboxAvatar.Add(this.alignment2);
            var w15 = ((Box.BoxChild) (this.hboxAvatar[this.alignment2]));
            w15.Position = 2;
            this.vbox6.Add(this.hboxAvatar);
            var w16 = ((Box.BoxChild) (this.vbox6[this.hboxAvatar]));
            w16.Position = 1;
            w16.Expand = false;
            w16.Fill = false;
            // Container child vbox6.Gtk.Box+BoxChild
            this.labelMessage = new Label();
            this.labelMessage.Name = "labelMessage";
            this.labelMessage.LabelProp = Catalog.GetString("Welcome to Flickr Downloadr. Click 'Login' to continue.");
            this.vbox6.Add(this.labelMessage);
            var w17 = ((Box.BoxChild) (this.vbox6[this.labelMessage]));
            w17.Position = 2;
            w17.Expand = false;
            w17.Fill = false;
            this.vbox5.Add(this.vbox6);
            var w18 = ((Box.BoxChild) (this.vbox5[this.vbox6]));
            w18.Position = 1;
            this.LoggedOutCanvas.Add(this.vbox5);
            var w19 = ((Box.BoxChild) (this.LoggedOutCanvas[this.vbox5]));
            w19.Position = 0;
            // Container child LoggedOutCanvas.Gtk.Box+BoxChild
            this.vbox2 = new VBox();
            this.vbox2.Name = "vbox2";
            this.vbox2.Spacing = 6;
            // Container child vbox2.Gtk.Box+BoxChild
            this.alignment9 = new Alignment(0.5F, 0.5F, 1F, 1F);
            this.alignment9.Name = "alignment9";
            this.vbox2.Add(this.alignment9);
            var w20 = ((Box.BoxChild) (this.vbox2[this.alignment9]));
            w20.Position = 0;
            // Container child vbox2.Gtk.Box+BoxChild
            this.hboxLogin = new HBox();
            this.hboxLogin.Name = "hboxLogin";
            this.hboxLogin.Spacing = 6;
            // Container child hboxLogin.Gtk.Box+BoxChild
            this.alignment5 = new Alignment(0.5F, 0.5F, 1F, 1F);
            this.alignment5.Name = "alignment5";
            this.hboxLogin.Add(this.alignment5);
            var w21 = ((Box.BoxChild) (this.hboxLogin[this.alignment5]));
            w21.Position = 0;
            // Container child hboxLogin.Gtk.Box+BoxChild
            this.buttonLogin = new Button();
            this.buttonLogin.WidthRequest = 130;
            this.buttonLogin.HeightRequest = 40;
            this.buttonLogin.CanFocus = true;
            this.buttonLogin.Name = "buttonLogin";
            this.buttonLogin.UseUnderline = true;
            this.buttonLogin.Label = Catalog.GetString("Login");
            this.hboxLogin.Add(this.buttonLogin);
            var w22 = ((Box.BoxChild) (this.hboxLogin[this.buttonLogin]));
            w22.Position = 1;
            w22.Expand = false;
            w22.Fill = false;
            // Container child hboxLogin.Gtk.Box+BoxChild
            this.alignment4 = new Alignment(0.5F, 0.5F, 1F, 1F);
            this.alignment4.Name = "alignment4";
            this.hboxLogin.Add(this.alignment4);
            var w23 = ((Box.BoxChild) (this.hboxLogin[this.alignment4]));
            w23.Position = 2;
            this.vbox2.Add(this.hboxLogin);
            var w24 = ((Box.BoxChild) (this.vbox2[this.hboxLogin]));
            w24.Position = 1;
            w24.Expand = false;
            w24.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.vbox7 = new VBox();
            this.vbox7.Name = "vbox7";
            this.vbox7.Spacing = 6;
            // Container child vbox7.Gtk.Box+BoxChild
            this.alignment3 = new Alignment(0.5F, 0.5F, 1F, 1F);
            this.alignment3.Name = "alignment3";
            this.vbox7.Add(this.alignment3);
            var w25 = ((Box.BoxChild) (this.vbox7[this.alignment3]));
            w25.Position = 0;
            // Container child vbox7.Gtk.Box+BoxChild
            this.hboxBottomButtons = new HBox();
            this.hboxBottomButtons.Name = "hboxBottomButtons";
            this.hboxBottomButtons.Homogeneous = true;
            this.hboxBottomButtons.Spacing = 6;
            // Container child hboxBottomButtons.Gtk.Box+BoxChild
            this.buttonLogout = new Button();
            this.buttonLogout.CanFocus = true;
            this.buttonLogout.Name = "buttonLogout";
            this.buttonLogout.UseUnderline = true;
            this.buttonLogout.Label = Catalog.GetString("Logout");
            this.hboxBottomButtons.Add(this.buttonLogout);
            var w26 = ((Box.BoxChild) (this.hboxBottomButtons[this.buttonLogout]));
            w26.Position = 0;
            w26.Expand = false;
            w26.Fill = false;
            // Container child hboxBottomButtons.Gtk.Box+BoxChild
            this.buttonPrefs = new Button();
            this.buttonPrefs.CanFocus = true;
            this.buttonPrefs.Name = "buttonPrefs";
            this.buttonPrefs.UseUnderline = true;
            this.buttonPrefs.Label = Catalog.GetString("Preferences");
            this.hboxBottomButtons.Add(this.buttonPrefs);
            var w27 = ((Box.BoxChild) (this.hboxBottomButtons[this.buttonPrefs]));
            w27.Position = 1;
            w27.Expand = false;
            w27.Fill = false;
            // Container child hboxBottomButtons.Gtk.Box+BoxChild
            this.buttonContinue = new Button();
            this.buttonContinue.CanFocus = true;
            this.buttonContinue.Name = "buttonContinue";
            this.buttonContinue.UseUnderline = true;
            this.buttonContinue.Label = Catalog.GetString("Continue");
            this.hboxBottomButtons.Add(this.buttonContinue);
            var w28 = ((Box.BoxChild) (this.hboxBottomButtons[this.buttonContinue]));
            w28.Position = 2;
            w28.Expand = false;
            w28.Fill = false;
            this.vbox7.Add(this.hboxBottomButtons);
            var w29 = ((Box.BoxChild) (this.vbox7[this.hboxBottomButtons]));
            w29.Position = 1;
            w29.Expand = false;
            w29.Fill = false;
            w29.Padding = 5;
            this.vbox2.Add(this.vbox7);
            var w30 = ((Box.BoxChild) (this.vbox2[this.vbox7]));
            w30.Position = 2;
            this.LoggedOutCanvas.Add(this.vbox2);
            var w31 = ((Box.BoxChild) (this.LoggedOutCanvas[this.vbox2]));
            w31.Position = 1;
            Add(this.LoggedOutCanvas);
            if ((Child != null)) {
                Child.ShowAll();
            }
            Show();
            DeleteEvent += OnDeleteEvent;
            this.buttonAbout.Clicked += buttonAboutClick;
            this.buttonLogin.Clicked += buttonLoginClick;
            this.buttonLogout.Clicked += buttonLogoutClick;
            this.buttonPrefs.Clicked += buttonPrefsClick;
            this.buttonContinue.Clicked += buttonContinueClick;
        }
    }
}
