
// This file has been generated by the GUI designer. Do not modify.
namespace FloydPink.Flickr.Downloadr
{
	public partial class LoginWindow
	{
		private global::Gtk.VBox LoggedOutCanvas;
		private global::Gtk.VBox vbox5;
		private global::Gtk.VBox vbox3;
		private global::Gtk.HBox hbox8;
		private global::Gtk.Alignment alignment8;
		private global::Gtk.Image image5;
		private global::Gtk.VBox vbox4;
		private global::Gtk.Button buttonAbout;
		private global::Gtk.VBox vbox6;
		private global::Gtk.Alignment alignment6;
		private global::Gtk.Alignment alignment11;
		private global::Gtk.Label label1;
		private global::Gtk.VBox vbox2;
		private global::Gtk.Alignment alignment9;
		private global::Gtk.HBox hbox5;
		private global::Gtk.Alignment alignment5;
		private global::Gtk.Button buttonLogin;
		private global::Gtk.Alignment alignment4;
		private global::Gtk.Alignment alignment10;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget FloydPink.Flickr.Downloadr.LoginWindow
			this.WidthRequest = 495;
			this.HeightRequest = 287;
			this.Name = "FloydPink.Flickr.Downloadr.LoginWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("Welcome - flickr downloadr");
			this.Icon = global::Gdk.Pixbuf.LoadFromResource ("FloydPink.Flickr.Downloadr.icon.png");
			this.TypeHint = ((global::Gdk.WindowTypeHint)(1));
			this.Resizable = false;
			this.AllowGrow = false;
			this.DefaultWidth = 495;
			this.DefaultHeight = 287;
			// Container child FloydPink.Flickr.Downloadr.LoginWindow.Gtk.Container+ContainerChild
			this.LoggedOutCanvas = new global::Gtk.VBox ();
			this.LoggedOutCanvas.Name = "LoggedOutCanvas";
			this.LoggedOutCanvas.Spacing = 6;
			// Container child LoggedOutCanvas.Gtk.Box+BoxChild
			this.vbox5 = new global::Gtk.VBox ();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			this.vbox3.BorderWidth = ((uint)(3));
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox8 = new global::Gtk.HBox ();
			this.hbox8.Name = "hbox8";
			this.hbox8.Spacing = 6;
			// Container child hbox8.Gtk.Box+BoxChild
			this.alignment8 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment8.Name = "alignment8";
			this.hbox8.Add (this.alignment8);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.alignment8]));
			w1.Position = 0;
			// Container child hbox8.Gtk.Box+BoxChild
			this.image5 = new global::Gtk.Image ();
			this.image5.Name = "image5";
			this.image5.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("FloydPink.Flickr.Downloadr.logo-Small.png");
			this.hbox8.Add (this.image5);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.image5]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.buttonAbout = new global::Gtk.Button ();
			this.buttonAbout.WidthRequest = 65;
			this.buttonAbout.HeightRequest = 35;
			this.buttonAbout.CanFocus = true;
			this.buttonAbout.Name = "buttonAbout";
			this.buttonAbout.UseUnderline = true;
			this.buttonAbout.Label = global::Mono.Unix.Catalog.GetString ("About");
			this.vbox4.Add (this.buttonAbout);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.buttonAbout]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			w3.Padding = ((uint)(5));
			this.hbox8.Add (this.vbox4);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.vbox4]));
			w4.Position = 2;
			w4.Expand = false;
			w4.Fill = false;
			this.vbox3.Add (this.hbox8);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox8]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			this.vbox5.Add (this.vbox3);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.vbox3]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.vbox6 = new global::Gtk.VBox ();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.alignment6 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment6.Name = "alignment6";
			this.vbox6.Add (this.alignment6);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.alignment6]));
			w7.Position = 0;
			// Container child vbox6.Gtk.Box+BoxChild
			this.alignment11 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment11.Name = "alignment11";
			this.vbox6.Add (this.alignment11);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.alignment11]));
			w8.Position = 1;
			// Container child vbox6.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Welcome to Flickr Downloadr. Click 'Login' to continue.");
			this.vbox6.Add (this.label1);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.label1]));
			w9.Position = 2;
			w9.Expand = false;
			w9.Fill = false;
			this.vbox5.Add (this.vbox6);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.vbox6]));
			w10.Position = 1;
			this.LoggedOutCanvas.Add (this.vbox5);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.LoggedOutCanvas [this.vbox5]));
			w11.Position = 0;
			// Container child LoggedOutCanvas.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.alignment9 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment9.Name = "alignment9";
			this.vbox2.Add (this.alignment9);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.alignment9]));
			w12.Position = 0;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox ();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.alignment5 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment5.Name = "alignment5";
			this.hbox5.Add (this.alignment5);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.alignment5]));
			w13.Position = 0;
			// Container child hbox5.Gtk.Box+BoxChild
			this.buttonLogin = new global::Gtk.Button ();
			this.buttonLogin.WidthRequest = 130;
			this.buttonLogin.HeightRequest = 40;
			this.buttonLogin.CanFocus = true;
			this.buttonLogin.Name = "buttonLogin";
			this.buttonLogin.UseUnderline = true;
			this.buttonLogin.Label = global::Mono.Unix.Catalog.GetString ("Login");
			this.hbox5.Add (this.buttonLogin);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.buttonLogin]));
			w14.Position = 1;
			w14.Expand = false;
			w14.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.alignment4 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment4.Name = "alignment4";
			this.hbox5.Add (this.alignment4);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.alignment4]));
			w15.Position = 2;
			this.vbox2.Add (this.hbox5);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox5]));
			w16.Position = 1;
			w16.Expand = false;
			w16.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.alignment10 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment10.Name = "alignment10";
			this.vbox2.Add (this.alignment10);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.alignment10]));
			w17.Position = 2;
			this.LoggedOutCanvas.Add (this.vbox2);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.LoggedOutCanvas [this.vbox2]));
			w18.Position = 1;
			this.Add (this.LoggedOutCanvas);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Show ();
			this.buttonLogin.Clicked += new global::System.EventHandler (this.buttonLoginClick);
		}
	}
}
