// This file has been generated by the GUI designer. Do not modify.
using Gtk;
using Mono.Unix;
using Stetic;

namespace FloydPink.Flickr.Downloadr {
    public partial class PhotoWidget {
        private Alignment GtkAlignment;
        private EventBox eventboxMain;
        private Label frameLabel;
        private Frame frameMain;
        private HBox hboxContainer;
        private Image imageMain;
        private VBox vboxContainer;

        protected virtual void Build() {
            Gui.Initialize(this);
            // Widget FloydPink.Flickr.Downloadr.PhotoWidget
            BinContainer.Attach(this);
            Name = "FloydPink.Flickr.Downloadr.PhotoWidget";
            // Container child FloydPink.Flickr.Downloadr.PhotoWidget.Gtk.Container+ContainerChild
            this.vboxContainer = new VBox();
            this.vboxContainer.Name = "vboxContainer";
            this.vboxContainer.Spacing = 10;
            // Container child vboxContainer.Gtk.Box+BoxChild
            this.hboxContainer = new HBox();
            this.hboxContainer.Name = "hboxContainer";
            this.hboxContainer.Spacing = 10;
            // Container child hboxContainer.Gtk.Box+BoxChild
            this.frameMain = new Frame();
            this.frameMain.Name = "frameMain";
            this.frameMain.LabelXalign = 0.95F;
            // Container child frameMain.Gtk.Container+ContainerChild
            this.GtkAlignment = new Alignment(0F, 0F, 1F, 1F);
            this.GtkAlignment.Name = "GtkAlignment";
            this.GtkAlignment.BottomPadding = 5;
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            this.eventboxMain = new EventBox();
            this.eventboxMain.Name = "eventboxMain";
            // Container child eventboxMain.Gtk.Container+ContainerChild
            this.imageMain = new Image();
            this.imageMain.Name = "imageMain";
            this.eventboxMain.Add(this.imageMain);
            this.GtkAlignment.Add(this.eventboxMain);
            this.frameMain.Add(this.GtkAlignment);
            this.frameLabel = new Label();
            this.frameLabel.Name = "frameLabel";
            this.frameLabel.LabelProp =
                Catalog.GetString("<span color=\"silver\" size=\"x-large\"><b><big> ☆ </big></b></span>");
            this.frameLabel.UseMarkup = true;
            this.frameMain.LabelWidget = this.frameLabel;
            this.hboxContainer.Add(this.frameMain);
            var w4 = ((Box.BoxChild) (this.hboxContainer[this.frameMain]));
            w4.Position = 0;
            w4.Padding = 5;
            this.vboxContainer.Add(this.hboxContainer);
            var w5 = ((Box.BoxChild) (this.vboxContainer[this.hboxContainer]));
            w5.Position = 0;
            Add(this.vboxContainer);
            if ((Child != null)) {
                Child.ShowAll();
            }
            Hide();
            this.eventboxMain.ButtonPressEvent += imageClick;
        }
    }
}
