// This file has been generated by the GUI designer. Do not modify.
using Gtk;
using Mono.Unix;
using Stetic;

namespace FloydPink.Flickr.Downloadr {
    public partial class SpinnerWidget {
        private Alignment alignment11;
        private Alignment alignment12;
        private Alignment alignment5;
        private Alignment alignment6;
        private Button buttonCancel;
        private HBox hboxPercent;
        private HBox hboxSpinner;
        private Image imageLoading;
        private Label labelOperation;
        private Label labelPercent;
        private VBox vbox8;
        private VBox vboxRoot;

        protected virtual void Build() {
            Gui.Initialize(this);
            // Widget FloydPink.Flickr.Downloadr.SpinnerWidget
            BinContainer.Attach(this);
            Name = "FloydPink.Flickr.Downloadr.SpinnerWidget";
            // Container child FloydPink.Flickr.Downloadr.SpinnerWidget.Gtk.Container+ContainerChild
            this.vboxRoot = new VBox();
            this.vboxRoot.Name = "vboxRoot";
            this.vboxRoot.Spacing = 6;
            // Container child vboxRoot.Gtk.Box+BoxChild
            this.hboxSpinner = new HBox();
            this.hboxSpinner.Name = "hboxSpinner";
            this.hboxSpinner.Spacing = 6;
            // Container child hboxSpinner.Gtk.Box+BoxChild
            this.alignment12 = new Alignment(0.5F, 0.5F, 1F, 1F);
            this.alignment12.Name = "alignment12";
            this.hboxSpinner.Add(this.alignment12);
            var w1 = ((Box.BoxChild) (this.hboxSpinner[this.alignment12]));
            w1.Position = 0;
            // Container child hboxSpinner.Gtk.Box+BoxChild
            this.imageLoading = new Image();
            this.imageLoading.Name = "imageLoading";
            this.hboxSpinner.Add(this.imageLoading);
            var w2 = ((Box.BoxChild) (this.hboxSpinner[this.imageLoading]));
            w2.Position = 1;
            w2.Expand = false;
            w2.Fill = false;
            // Container child hboxSpinner.Gtk.Box+BoxChild
            this.labelOperation = new Label();
            this.labelOperation.Name = "labelOperation";
            this.labelOperation.Xalign = 0F;
            this.labelOperation.LabelProp = Catalog.GetString("Please wait...");
            this.hboxSpinner.Add(this.labelOperation);
            var w3 = ((Box.BoxChild) (this.hboxSpinner[this.labelOperation]));
            w3.Position = 2;
            w3.Expand = false;
            // Container child hboxSpinner.Gtk.Box+BoxChild
            this.alignment11 = new Alignment(0.5F, 0.5F, 1F, 1F);
            this.alignment11.Name = "alignment11";
            this.hboxSpinner.Add(this.alignment11);
            var w4 = ((Box.BoxChild) (this.hboxSpinner[this.alignment11]));
            w4.Position = 3;
            this.vboxRoot.Add(this.hboxSpinner);
            var w5 = ((Box.BoxChild) (this.vboxRoot[this.hboxSpinner]));
            w5.Position = 1;
            w5.Expand = false;
            w5.Fill = false;
            // Container child vboxRoot.Gtk.Box+BoxChild
            this.hboxPercent = new HBox();
            this.hboxPercent.Name = "hboxPercent";
            this.hboxPercent.Spacing = 6;
            // Container child hboxPercent.Gtk.Box+BoxChild
            this.alignment6 = new Alignment(0.5F, 0.5F, 1F, 1F);
            this.alignment6.Name = "alignment6";
            this.hboxPercent.Add(this.alignment6);
            var w6 = ((Box.BoxChild) (this.hboxPercent[this.alignment6]));
            w6.Position = 0;
            // Container child hboxPercent.Gtk.Box+BoxChild
            this.labelPercent = new Label();
            this.labelPercent.Name = "labelPercent";
            this.labelPercent.LabelProp = Catalog.GetString("Percent Done");
            this.hboxPercent.Add(this.labelPercent);
            var w7 = ((Box.BoxChild) (this.hboxPercent[this.labelPercent]));
            w7.Position = 1;
            w7.Expand = false;
            w7.Fill = false;
            // Container child hboxPercent.Gtk.Box+BoxChild
            this.vbox8 = new VBox();
            this.vbox8.Name = "vbox8";
            this.vbox8.Spacing = 6;
            // Container child vbox8.Gtk.Box+BoxChild
            this.buttonCancel = new Button();
            this.buttonCancel.CanFocus = true;
            this.buttonCancel.Name = "buttonCancel";
            this.buttonCancel.UseUnderline = true;
            this.buttonCancel.Label = Catalog.GetString("Cancel");
            this.vbox8.Add(this.buttonCancel);
            var w8 = ((Box.BoxChild) (this.vbox8[this.buttonCancel]));
            w8.Position = 0;
            w8.Expand = false;
            w8.Fill = false;
            this.hboxPercent.Add(this.vbox8);
            var w9 = ((Box.BoxChild) (this.hboxPercent[this.vbox8]));
            w9.Position = 2;
            w9.Expand = false;
            w9.Fill = false;
            // Container child hboxPercent.Gtk.Box+BoxChild
            this.alignment5 = new Alignment(0.5F, 0.5F, 1F, 1F);
            this.alignment5.Name = "alignment5";
            this.hboxPercent.Add(this.alignment5);
            var w10 = ((Box.BoxChild) (this.hboxPercent[this.alignment5]));
            w10.Position = 3;
            this.vboxRoot.Add(this.hboxPercent);
            var w11 = ((Box.BoxChild) (this.vboxRoot[this.hboxPercent]));
            w11.Position = 2;
            w11.Expand = false;
            w11.Fill = false;
            Add(this.vboxRoot);
            if ((Child != null)) {
                Child.ShowAll();
            }
            Hide();
            this.buttonCancel.Clicked += buttonCancelClick;
        }
    }
}
