// This file has been generated by the GUI designer. Do not modify.
using Gdk;
using Gtk;
using Mono.Unix;
using Stetic;

namespace FloydPink.Flickr.Downloadr {
    public partial class BrowserWindow {
        private Alignment alignment1;
        private Button buttonBack;
        private Button buttonDownloadAllPages;
        private Button buttonDownloadSelection;
        private Button buttonDownloadThisPage;
        private Button buttonFirstPage;
        private Button buttonLastPage;
        private Button buttonNextPage;
        private Button buttonPreviousPage;
        private Button buttonSelectAll;
        private Button buttonUnSelectAll;
        private HBox hbox5;
        private HBox hbox6;
        private HBox hboxBottom;
        private HBox hboxButtons;
        private HBox hboxCenter;
        private HBox hboxLeft;
        private HBox hboxRight;
        private HBox hboxSpinner;
        private Label label1;
        private Label labelPages;
        private Label labelPhotos;
        private ScrolledWindow scrolledwindowPhotos;
        private ToggleButton togglebuttonShowAllPhotos;
        private VBox vbox4;
        private VBox vboxPhotos;
        private VBox vboxRoot;

        protected virtual void Build() {
            Gui.Initialize(this);
            // Widget FloydPink.Flickr.Downloadr.BrowserWindow
            HeightRequest = 600;
            Name = "FloydPink.Flickr.Downloadr.BrowserWindow";
            Title = Catalog.GetString("Photo Browser - flickr downloadr");
            Icon = Pixbuf.LoadFromResource("FloydPink.Flickr.Downloadr.Assets.icon.png");
            WindowPosition = ((WindowPosition) (3));
            Resizable = false;
            AllowGrow = false;
            // Container child FloydPink.Flickr.Downloadr.BrowserWindow.Gtk.Container+ContainerChild
            this.vboxRoot = new VBox();
            this.vboxRoot.Name = "vboxRoot";
            this.vboxRoot.Spacing = 6;
            this.vboxRoot.BorderWidth = 10;
            // Container child vboxRoot.Gtk.Box+BoxChild
            this.hboxSpinner = new HBox();
            this.hboxSpinner.Name = "hboxSpinner";
            this.hboxSpinner.Spacing = 6;
            this.vboxRoot.Add(this.hboxSpinner);
            var w1 = ((Box.BoxChild) (this.vboxRoot[this.hboxSpinner]));
            w1.Position = 0;
            w1.Expand = false;
            w1.Fill = false;
            // Container child vboxRoot.Gtk.Box+BoxChild
            this.hbox6 = new HBox();
            this.hbox6.Name = "hbox6";
            this.hbox6.Spacing = 6;
            // Container child hbox6.Gtk.Box+BoxChild
            this.scrolledwindowPhotos = new ScrolledWindow();
            this.scrolledwindowPhotos.CanFocus = true;
            this.scrolledwindowPhotos.Name = "scrolledwindowPhotos";
            this.scrolledwindowPhotos.ShadowType = ((ShadowType) (1));
            // Container child scrolledwindowPhotos.Gtk.Container+ContainerChild
            var w2 = new Viewport();
            w2.ShadowType = 0;
            // Container child GtkViewport.Gtk.Container+ContainerChild
            this.vboxPhotos = new VBox();
            this.vboxPhotos.Name = "vboxPhotos";
            this.vboxPhotos.Homogeneous = true;
            this.vboxPhotos.Spacing = 6;
            w2.Add(this.vboxPhotos);
            this.scrolledwindowPhotos.Add(w2);
            this.hbox6.Add(this.scrolledwindowPhotos);
            var w5 = ((Box.BoxChild) (this.hbox6[this.scrolledwindowPhotos]));
            w5.Position = 0;
            this.vboxRoot.Add(this.hbox6);
            var w6 = ((Box.BoxChild) (this.vboxRoot[this.hbox6]));
            w6.Position = 1;
            // Container child vboxRoot.Gtk.Box+BoxChild
            this.hboxBottom = new HBox();
            this.hboxBottom.Name = "hboxBottom";
            this.hboxBottom.Spacing = 6;
            // Container child hboxBottom.Gtk.Box+BoxChild
            this.hboxButtons = new HBox();
            this.hboxButtons.Name = "hboxButtons";
            this.hboxButtons.Homogeneous = true;
            this.hboxButtons.Spacing = 6;
            // Container child hboxButtons.Gtk.Box+BoxChild
            this.hboxLeft = new HBox();
            this.hboxLeft.Name = "hboxLeft";
            this.hboxLeft.Spacing = 6;
            // Container child hboxLeft.Gtk.Box+BoxChild
            this.buttonBack = new Button();
            this.buttonBack.WidthRequest = 65;
            this.buttonBack.CanFocus = true;
            this.buttonBack.Name = "buttonBack";
            this.buttonBack.UseUnderline = true;
            this.buttonBack.Label = Catalog.GetString("Back");
            this.hboxLeft.Add(this.buttonBack);
            var w7 = ((Box.BoxChild) (this.hboxLeft[this.buttonBack]));
            w7.Position = 0;
            w7.Expand = false;
            w7.Fill = false;
            // Container child hboxLeft.Gtk.Box+BoxChild
            this.togglebuttonShowAllPhotos = new ToggleButton();
            this.togglebuttonShowAllPhotos.WidthRequest = 185;
            this.togglebuttonShowAllPhotos.CanFocus = true;
            this.togglebuttonShowAllPhotos.Name = "togglebuttonShowAllPhotos";
            this.togglebuttonShowAllPhotos.UseUnderline = true;
            this.togglebuttonShowAllPhotos.FocusOnClick = false;
            this.togglebuttonShowAllPhotos.Label = Catalog.GetString("Show All Photos");
            this.hboxLeft.Add(this.togglebuttonShowAllPhotos);
            var w8 = ((Box.BoxChild) (this.hboxLeft[this.togglebuttonShowAllPhotos]));
            w8.Position = 1;
            w8.Expand = false;
            w8.Fill = false;
            // Container child hboxLeft.Gtk.Box+BoxChild
            this.hbox5 = new HBox();
            this.hbox5.Name = "hbox5";
            this.hbox5.Spacing = 6;
            // Container child hbox5.Gtk.Box+BoxChild
            this.buttonSelectAll = new Button();
            this.buttonSelectAll.WidthRequest = 35;
            this.buttonSelectAll.CanFocus = true;
            this.buttonSelectAll.Name = "buttonSelectAll";
            this.buttonSelectAll.UseUnderline = true;
            this.buttonSelectAll.FocusOnClick = false;
            this.buttonSelectAll.Label = Catalog.GetString("✓");
            this.hbox5.Add(this.buttonSelectAll);
            var w9 = ((Box.BoxChild) (this.hbox5[this.buttonSelectAll]));
            w9.Position = 0;
            w9.Expand = false;
            w9.Fill = false;
            // Container child hbox5.Gtk.Box+BoxChild
            this.buttonUnSelectAll = new Button();
            this.buttonUnSelectAll.WidthRequest = 35;
            this.buttonUnSelectAll.Sensitive = false;
            this.buttonUnSelectAll.CanFocus = true;
            this.buttonUnSelectAll.Name = "buttonUnSelectAll";
            this.buttonUnSelectAll.UseUnderline = true;
            this.buttonUnSelectAll.FocusOnClick = false;
            this.buttonUnSelectAll.Label = Catalog.GetString("X");
            this.hbox5.Add(this.buttonUnSelectAll);
            var w10 = ((Box.BoxChild) (this.hbox5[this.buttonUnSelectAll]));
            w10.Position = 1;
            w10.Expand = false;
            w10.Fill = false;
            // Container child hbox5.Gtk.Box+BoxChild
            this.alignment1 = new Alignment(0.5F, 0.5F, 1F, 1F);
            this.alignment1.Name = "alignment1";
            this.hbox5.Add(this.alignment1);
            var w11 = ((Box.BoxChild) (this.hbox5[this.alignment1]));
            w11.Position = 2;
            this.hboxLeft.Add(this.hbox5);
            var w12 = ((Box.BoxChild) (this.hboxLeft[this.hbox5]));
            w12.Position = 2;
            this.hboxButtons.Add(this.hboxLeft);
            var w13 = ((Box.BoxChild) (this.hboxButtons[this.hboxLeft]));
            w13.Position = 0;
            // Container child hboxButtons.Gtk.Box+BoxChild
            this.hboxCenter = new HBox();
            this.hboxCenter.Name = "hboxCenter";
            this.hboxCenter.Spacing = 6;
            // Container child hboxCenter.Gtk.Box+BoxChild
            this.buttonFirstPage = new Button();
            this.buttonFirstPage.WidthRequest = 35;
            this.buttonFirstPage.CanFocus = true;
            this.buttonFirstPage.Name = "buttonFirstPage";
            this.buttonFirstPage.UseUnderline = true;
            this.buttonFirstPage.FocusOnClick = false;
            this.buttonFirstPage.Label = Catalog.GetString("|<<");
            this.hboxCenter.Add(this.buttonFirstPage);
            var w14 = ((Box.BoxChild) (this.hboxCenter[this.buttonFirstPage]));
            w14.Position = 0;
            w14.Expand = false;
            w14.Fill = false;
            // Container child hboxCenter.Gtk.Box+BoxChild
            this.buttonPreviousPage = new Button();
            this.buttonPreviousPage.WidthRequest = 35;
            this.buttonPreviousPage.CanFocus = true;
            this.buttonPreviousPage.Name = "buttonPreviousPage";
            this.buttonPreviousPage.UseUnderline = true;
            this.buttonPreviousPage.FocusOnClick = false;
            this.buttonPreviousPage.Label = Catalog.GetString("<");
            this.hboxCenter.Add(this.buttonPreviousPage);
            var w15 = ((Box.BoxChild) (this.hboxCenter[this.buttonPreviousPage]));
            w15.Position = 1;
            w15.Expand = false;
            w15.Fill = false;
            // Container child hboxCenter.Gtk.Box+BoxChild
            this.vbox4 = new VBox();
            this.vbox4.Name = "vbox4";
            this.vbox4.Spacing = 6;
            // Container child vbox4.Gtk.Box+BoxChild
            this.labelPhotos = new Label();
            this.labelPhotos.Name = "labelPhotos";
            this.labelPhotos.LabelProp = Catalog.GetString("<small>                       </small>");
            this.labelPhotos.UseMarkup = true;
            this.vbox4.Add(this.labelPhotos);
            var w16 = ((Box.BoxChild) (this.vbox4[this.labelPhotos]));
            w16.Position = 0;
            // Container child vbox4.Gtk.Box+BoxChild
            this.labelPages = new Label();
            this.labelPages.Name = "labelPages";
            this.labelPages.LabelProp = Catalog.GetString("<small>                       </small>");
            this.labelPages.UseMarkup = true;
            this.vbox4.Add(this.labelPages);
            var w17 = ((Box.BoxChild) (this.vbox4[this.labelPages]));
            w17.Position = 1;
            this.hboxCenter.Add(this.vbox4);
            var w18 = ((Box.BoxChild) (this.hboxCenter[this.vbox4]));
            w18.Position = 2;
            // Container child hboxCenter.Gtk.Box+BoxChild
            this.buttonNextPage = new Button();
            this.buttonNextPage.WidthRequest = 35;
            this.buttonNextPage.CanFocus = true;
            this.buttonNextPage.Name = "buttonNextPage";
            this.buttonNextPage.UseUnderline = true;
            this.buttonNextPage.FocusOnClick = false;
            this.buttonNextPage.Label = Catalog.GetString(">");
            this.hboxCenter.Add(this.buttonNextPage);
            var w19 = ((Box.BoxChild) (this.hboxCenter[this.buttonNextPage]));
            w19.Position = 3;
            w19.Expand = false;
            w19.Fill = false;
            // Container child hboxCenter.Gtk.Box+BoxChild
            this.buttonLastPage = new Button();
            this.buttonLastPage.WidthRequest = 35;
            this.buttonLastPage.CanFocus = true;
            this.buttonLastPage.Name = "buttonLastPage";
            this.buttonLastPage.UseUnderline = true;
            this.buttonLastPage.FocusOnClick = false;
            this.buttonLastPage.Label = Catalog.GetString(">>|");
            this.hboxCenter.Add(this.buttonLastPage);
            var w20 = ((Box.BoxChild) (this.hboxCenter[this.buttonLastPage]));
            w20.Position = 4;
            w20.Expand = false;
            w20.Fill = false;
            this.hboxButtons.Add(this.hboxCenter);
            var w21 = ((Box.BoxChild) (this.hboxButtons[this.hboxCenter]));
            w21.Position = 1;
            w21.Expand = false;
            w21.Fill = false;
            // Container child hboxButtons.Gtk.Box+BoxChild
            this.hboxRight = new HBox();
            this.hboxRight.Name = "hboxRight";
            this.hboxRight.Spacing = 6;
            // Container child hboxRight.Gtk.Box+BoxChild
            this.label1 = new Label();
            this.label1.Name = "label1";
            this.label1.LabelProp = Catalog.GetString("<b>Download</b>");
            this.label1.UseMarkup = true;
            this.hboxRight.Add(this.label1);
            var w22 = ((Box.BoxChild) (this.hboxRight[this.label1]));
            w22.Position = 0;
            w22.Expand = false;
            w22.Fill = false;
            // Container child hboxRight.Gtk.Box+BoxChild
            this.buttonDownloadSelection = new Button();
            this.buttonDownloadSelection.WidthRequest = 125;
            this.buttonDownloadSelection.CanFocus = true;
            this.buttonDownloadSelection.Name = "buttonDownloadSelection";
            this.buttonDownloadSelection.UseUnderline = true;
            this.buttonDownloadSelection.FocusOnClick = false;
            this.buttonDownloadSelection.Label = Catalog.GetString("Selection");
            this.hboxRight.Add(this.buttonDownloadSelection);
            var w23 = ((Box.BoxChild) (this.hboxRight[this.buttonDownloadSelection]));
            w23.Position = 1;
            w23.Expand = false;
            w23.Fill = false;
            // Container child hboxRight.Gtk.Box+BoxChild
            this.buttonDownloadThisPage = new Button();
            this.buttonDownloadThisPage.WidthRequest = 76;
            this.buttonDownloadThisPage.CanFocus = true;
            this.buttonDownloadThisPage.Name = "buttonDownloadThisPage";
            this.buttonDownloadThisPage.UseUnderline = true;
            this.buttonDownloadThisPage.FocusOnClick = false;
            this.buttonDownloadThisPage.Label = Catalog.GetString("This Page");
            this.hboxRight.Add(this.buttonDownloadThisPage);
            var w24 = ((Box.BoxChild) (this.hboxRight[this.buttonDownloadThisPage]));
            w24.Position = 2;
            w24.Expand = false;
            w24.Fill = false;
            // Container child hboxRight.Gtk.Box+BoxChild
            this.buttonDownloadAllPages = new Button();
            this.buttonDownloadAllPages.WidthRequest = 75;
            this.buttonDownloadAllPages.CanFocus = true;
            this.buttonDownloadAllPages.Name = "buttonDownloadAllPages";
            this.buttonDownloadAllPages.UseUnderline = true;
            this.buttonDownloadAllPages.FocusOnClick = false;
            this.buttonDownloadAllPages.Label = Catalog.GetString("All Pages");
            this.hboxRight.Add(this.buttonDownloadAllPages);
            var w25 = ((Box.BoxChild) (this.hboxRight[this.buttonDownloadAllPages]));
            w25.Position = 3;
            w25.Expand = false;
            w25.Fill = false;
            this.hboxButtons.Add(this.hboxRight);
            var w26 = ((Box.BoxChild) (this.hboxButtons[this.hboxRight]));
            w26.Position = 2;
            w26.Fill = false;
            this.hboxBottom.Add(this.hboxButtons);
            var w27 = ((Box.BoxChild) (this.hboxBottom[this.hboxButtons]));
            w27.Position = 0;
            this.vboxRoot.Add(this.hboxBottom);
            var w28 = ((Box.BoxChild) (this.vboxRoot[this.hboxBottom]));
            w28.Position = 2;
            w28.Expand = false;
            w28.Fill = false;
            Add(this.vboxRoot);
            if ((Child != null)) {
                Child.ShowAll();
            }
            DefaultWidth = 1119;
            DefaultHeight = 600;
            Show();
            DeleteEvent += OnDeleteEvent;
            this.buttonBack.Clicked += buttonBackClick;
            this.togglebuttonShowAllPhotos.Clicked += togglebuttonShowAllPhotosClick;
            this.buttonSelectAll.Clicked += buttonSelectAllClick;
            this.buttonUnSelectAll.Clicked += buttonUnSelectAllClick;
            this.buttonFirstPage.Clicked += buttonFirstPageClick;
            this.buttonPreviousPage.Clicked += buttonPreviousPageClick;
            this.buttonNextPage.Clicked += buttonNextPageClick;
            this.buttonLastPage.Clicked += buttonLastPageClick;
            this.buttonDownloadSelection.Clicked += buttonDownloadSelectionClick;
            this.buttonDownloadThisPage.Clicked += buttonDownloadThisPageClick;
            this.buttonDownloadAllPages.Clicked += buttonDownloadAllPagesClick;
        }
    }
}
