// This file has been generated by the GUI designer. Do not modify.
using Gdk;
using Gtk;
using Mono.Unix;
using Stetic;
using Image = Gtk.Image;

namespace FloydPink.Flickr.Downloadr {
    public partial class FatalErrorWindow {
        private Alignment alignment5;
        private Alignment alignment6;
        private Alignment alignment7;
        private Alignment alignment8;
        private HBox hbox6;
        private Image image3;
        private VBox vbox4;

        protected virtual void Build() {
            Gui.Initialize(this);
            // Widget FloydPink.Flickr.Downloadr.FatalErrorWindow
            WidthRequest = 320;
            HeightRequest = 200;
            Name = "FloydPink.Flickr.Downloadr.FatalErrorWindow";
            Title = Catalog.GetString("Fatal Error - flickr downloadr");
            Icon = Pixbuf.LoadFromResource("FloydPink.Flickr.Downloadr.Assets.icon.png");
            TypeHint = ((WindowTypeHint) (1));
            WindowPosition = ((WindowPosition) (1));
            Resizable = false;
            AllowGrow = false;
            // Container child FloydPink.Flickr.Downloadr.FatalErrorWindow.Gtk.Container+ContainerChild
            this.vbox4 = new VBox();
            this.vbox4.Name = "vbox4";
            this.vbox4.Spacing = 6;
            // Container child vbox4.Gtk.Box+BoxChild
            this.alignment5 = new Alignment(0.5F, 0.5F, 1F, 1F);
            this.alignment5.Name = "alignment5";
            this.vbox4.Add(this.alignment5);
            var w1 = ((Box.BoxChild) (this.vbox4[this.alignment5]));
            w1.Position = 0;
            // Container child vbox4.Gtk.Box+BoxChild
            this.hbox6 = new HBox();
            this.hbox6.Name = "hbox6";
            this.hbox6.Spacing = 6;
            // Container child hbox6.Gtk.Box+BoxChild
            this.alignment8 = new Alignment(0.5F, 0.5F, 1F, 1F);
            this.alignment8.Name = "alignment8";
            this.hbox6.Add(this.alignment8);
            var w2 = ((Box.BoxChild) (this.hbox6[this.alignment8]));
            w2.Position = 0;
            // Container child hbox6.Gtk.Box+BoxChild
            this.image3 = new Image();
            this.image3.Name = "image3";
            this.image3.Pixbuf = Pixbuf.LoadFromResource("FloydPink.Flickr.Downloadr.Assets.fatal-error.png");
            this.hbox6.Add(this.image3);
            var w3 = ((Box.BoxChild) (this.hbox6[this.image3]));
            w3.Position = 1;
            w3.Expand = false;
            w3.Fill = false;
            // Container child hbox6.Gtk.Box+BoxChild
            this.alignment7 = new Alignment(0.5F, 0.5F, 1F, 1F);
            this.alignment7.Name = "alignment7";
            this.hbox6.Add(this.alignment7);
            var w4 = ((Box.BoxChild) (this.hbox6[this.alignment7]));
            w4.Position = 2;
            this.vbox4.Add(this.hbox6);
            var w5 = ((Box.BoxChild) (this.vbox4[this.hbox6]));
            w5.Position = 1;
            w5.Expand = false;
            w5.Fill = false;
            // Container child vbox4.Gtk.Box+BoxChild
            this.alignment6 = new Alignment(0.5F, 0.5F, 1F, 1F);
            this.alignment6.Name = "alignment6";
            this.vbox4.Add(this.alignment6);
            var w6 = ((Box.BoxChild) (this.vbox4[this.alignment6]));
            w6.Position = 2;
            Add(this.vbox4);
            if ((Child != null)) {
                Child.ShowAll();
            }
            DefaultWidth = 480;
            DefaultHeight = 640;
            Show();
        }
    }
}
