// This file has been generated by the GUI designer. Do not modify.
using System;
using Gdk;
using GLib;
using Gtk;
using Mono.Unix;
using Stetic;

namespace FloydPink.Flickr.Downloadr {
    public partial class PreferencesWindow {
        private Alignment alignment3;
        private Alignment alignment4;
        private Button buttonCacheLocation;
        private Button buttonCancel;
        private Button buttonDefaults;
        private Button buttonDownloadLocation;
        private Button buttonEmptyCache;
        private Button buttonSave;
        private CheckButton checkbuttonDescription;
        private CheckButton checkbuttonTags;
        private CheckButton checkbuttonTitle;
        private ComboBox comboboxDownloadSize;
        private ComboBox comboboxPhotosPerPage;
        private ComboBox comboboxSafetyLevel;
        private Entry entryCacheLocation;
        private Entry entryDownloadLocation;
        private Fixed fixed3;
        private Fixed fixed5;
        private HBox hbox1;
        private HBox hbox2;
        private HBox hbox3;
        private HBox hbox4;
        private HBox hbox5;
        private HBox hbox6;
        private HBox hbox7;
        private HBox hbox8;
        private HBox hbox9;
        private Label label3;
        private Label label9;
        private Label labelCacheLocation;
        private Label labelCacheSize;
        private Label labelCacheSizeValue;
        private Label labelDownloadLocation;
        private Label labelDownloadSize;
        private Label labelFilename;
        private Label labelMetadata;
        private Label labelPhotosPerPage;
        private Label labelSafetyLevel;
        private Label labelTags;
        private RadioButton radioPhotoId;
        private RadioButton radioPhotoTitle;
        private RadioButton radioTagsInternal;
        private RadioButton radioTagsOriginal;
        private VBox vbox11;
        private VBox vbox12;
        private VBox vbox13;
        private VBox vbox9;

        protected virtual void Build() {
            Gui.Initialize(this);
            // Widget FloydPink.Flickr.Downloadr.PreferencesWindow
            HeightRequest = 510;
            Name = "FloydPink.Flickr.Downloadr.PreferencesWindow";
            Title = Catalog.GetString("Preferences - flickr downloadr");
            Icon = Pixbuf.LoadFromResource("FloydPink.Flickr.Downloadr.Assets.icon.png");
            WindowPosition = ((WindowPosition) (3));
            Resizable = false;
            AllowGrow = false;
            // Container child FloydPink.Flickr.Downloadr.PreferencesWindow.Gtk.Container+ContainerChild
            this.vbox9 = new VBox();
            this.vbox9.Name = "vbox9";
            this.vbox9.Spacing = 6;
            // Container child vbox9.Gtk.Box+BoxChild
            this.fixed3 = new Fixed();
            this.fixed3.Name = "fixed3";
            this.fixed3.HasWindow = false;
            this.vbox9.Add(this.fixed3);
            var w1 = ((Box.BoxChild) (this.vbox9[this.fixed3]));
            w1.Position = 0;
            w1.Expand = false;
            w1.Fill = false;
            // Container child vbox9.Gtk.Box+BoxChild
            this.label3 = new Label();
            this.label3.Name = "label3";
            this.label3.Xalign = 0.05F;
            this.label3.LabelProp = Catalog.GetString("<big><b><u>Preferences</u></b></big>");
            this.label3.UseMarkup = true;
            this.vbox9.Add(this.label3);
            var w2 = ((Box.BoxChild) (this.vbox9[this.label3]));
            w2.Position = 1;
            w2.Expand = false;
            w2.Fill = false;
            // Container child vbox9.Gtk.Box+BoxChild
            this.hbox1 = new HBox();
            this.hbox1.Name = "hbox1";
            this.hbox1.Spacing = 6;
            // Container child hbox1.Gtk.Box+BoxChild
            this.alignment4 = new Alignment(0.5F, 0.5F, 1F, 1F);
            this.alignment4.Name = "alignment4";
            this.hbox1.Add(this.alignment4);
            var w3 = ((Box.BoxChild) (this.hbox1[this.alignment4]));
            w3.Position = 0;
            // Container child hbox1.Gtk.Box+BoxChild
            this.vbox11 = new VBox();
            this.vbox11.Name = "vbox11";
            this.vbox11.Homogeneous = true;
            this.vbox11.Spacing = 6;
            // Container child vbox11.Gtk.Box+BoxChild
            this.vbox12 = new VBox();
            this.vbox12.Name = "vbox12";
            this.vbox12.Homogeneous = true;
            this.vbox12.Spacing = 6;
            // Container child vbox12.Gtk.Box+BoxChild
            this.labelFilename = new Label();
            this.labelFilename.Name = "labelFilename";
            this.labelFilename.Xalign = 0F;
            this.labelFilename.LabelProp = Catalog.GetString("Filename:");
            this.vbox12.Add(this.labelFilename);
            var w4 = ((Box.BoxChild) (this.vbox12[this.labelFilename]));
            w4.Position = 0;
            // Container child vbox12.Gtk.Box+BoxChild
            this.labelDownloadLocation = new Label();
            this.labelDownloadLocation.Name = "labelDownloadLocation";
            this.labelDownloadLocation.Xalign = 0F;
            this.labelDownloadLocation.LabelProp = Catalog.GetString("Download Location:");
            this.vbox12.Add(this.labelDownloadLocation);
            var w5 = ((Box.BoxChild) (this.vbox12[this.labelDownloadLocation]));
            w5.Position = 1;
            // Container child vbox12.Gtk.Box+BoxChild
            this.labelDownloadSize = new Label();
            this.labelDownloadSize.Name = "labelDownloadSize";
            this.labelDownloadSize.Xalign = 0F;
            this.labelDownloadSize.LabelProp = Catalog.GetString("Download Size:");
            this.vbox12.Add(this.labelDownloadSize);
            var w6 = ((Box.BoxChild) (this.vbox12[this.labelDownloadSize]));
            w6.Position = 2;
            // Container child vbox12.Gtk.Box+BoxChild
            this.labelMetadata = new Label();
            this.labelMetadata.Name = "labelMetadata";
            this.labelMetadata.Xalign = 0F;
            this.labelMetadata.LabelProp = Catalog.GetString("Metadata:");
            this.vbox12.Add(this.labelMetadata);
            var w7 = ((Box.BoxChild) (this.vbox12[this.labelMetadata]));
            w7.Position = 3;
            // Container child vbox12.Gtk.Box+BoxChild
            this.label9 = new Label();
            this.label9.Name = "label9";
            this.label9.Xalign = 0F;
            this.vbox12.Add(this.label9);
            var w8 = ((Box.BoxChild) (this.vbox12[this.label9]));
            w8.Position = 4;
            // Container child vbox12.Gtk.Box+BoxChild
            this.labelCacheSize = new Label();
            this.labelCacheSize.Name = "labelCacheSize";
            this.labelCacheSize.Xalign = 0F;
            this.labelCacheSize.LabelProp = Catalog.GetString("Cache Size:");
            this.vbox12.Add(this.labelCacheSize);
            var w9 = ((Box.BoxChild) (this.vbox12[this.labelCacheSize]));
            w9.PackType = ((PackType) (1));
            w9.Position = 5;
            // Container child vbox12.Gtk.Box+BoxChild
            this.labelCacheLocation = new Label();
            this.labelCacheLocation.Name = "labelCacheLocation";
            this.labelCacheLocation.Xalign = 0F;
            this.labelCacheLocation.LabelProp = Catalog.GetString("Cache Location:");
            this.vbox12.Add(this.labelCacheLocation);
            var w10 = ((Box.BoxChild) (this.vbox12[this.labelCacheLocation]));
            w10.PackType = ((PackType) (1));
            w10.Position = 6;
            // Container child vbox12.Gtk.Box+BoxChild
            this.labelTags = new Label();
            this.labelTags.Name = "labelTags";
            this.labelTags.Xalign = 0F;
            this.labelTags.LabelProp = Catalog.GetString("Tags:");
            this.vbox12.Add(this.labelTags);
            var w11 = ((Box.BoxChild) (this.vbox12[this.labelTags]));
            w11.PackType = ((PackType) (1));
            w11.Position = 7;
            // Container child vbox12.Gtk.Box+BoxChild
            this.labelSafetyLevel = new Label();
            this.labelSafetyLevel.Name = "labelSafetyLevel";
            this.labelSafetyLevel.Xalign = 0F;
            this.labelSafetyLevel.LabelProp = Catalog.GetString("Safety Level:");
            this.vbox12.Add(this.labelSafetyLevel);
            var w12 = ((Box.BoxChild) (this.vbox12[this.labelSafetyLevel]));
            w12.PackType = ((PackType) (1));
            w12.Position = 8;
            // Container child vbox12.Gtk.Box+BoxChild
            this.labelPhotosPerPage = new Label();
            this.labelPhotosPerPage.Name = "labelPhotosPerPage";
            this.labelPhotosPerPage.Xalign = 0F;
            this.labelPhotosPerPage.LabelProp = Catalog.GetString("Photos Per Page:");
            this.vbox12.Add(this.labelPhotosPerPage);
            var w13 = ((Box.BoxChild) (this.vbox12[this.labelPhotosPerPage]));
            w13.PackType = ((PackType) (1));
            w13.Position = 9;
            this.vbox11.Add(this.vbox12);
            var w14 = ((Box.BoxChild) (this.vbox11[this.vbox12]));
            w14.Position = 0;
            w14.Expand = false;
            this.hbox1.Add(this.vbox11);
            var w15 = ((Box.BoxChild) (this.hbox1[this.vbox11]));
            w15.Position = 1;
            w15.Expand = false;
            w15.Fill = false;
            // Container child hbox1.Gtk.Box+BoxChild
            this.vbox13 = new VBox();
            this.vbox13.Name = "vbox13";
            this.vbox13.Homogeneous = true;
            this.vbox13.Spacing = 6;
            // Container child vbox13.Gtk.Box+BoxChild
            this.hbox3 = new HBox();
            this.hbox3.Name = "hbox3";
            this.hbox3.Spacing = 6;
            // Container child hbox3.Gtk.Box+BoxChild
            this.radioPhotoId = new RadioButton(Catalog.GetString("Photo ID"));
            this.radioPhotoId.CanFocus = true;
            this.radioPhotoId.Name = "radioPhotoId";
            this.radioPhotoId.DrawIndicator = true;
            this.radioPhotoId.UseUnderline = true;
            this.radioPhotoId.Group = new SList(IntPtr.Zero);
            this.hbox3.Add(this.radioPhotoId);
            var w16 = ((Box.BoxChild) (this.hbox3[this.radioPhotoId]));
            w16.Position = 0;
            // Container child hbox3.Gtk.Box+BoxChild
            this.radioPhotoTitle = new RadioButton(Catalog.GetString("Photo Title"));
            this.radioPhotoTitle.CanFocus = true;
            this.radioPhotoTitle.Name = "radioPhotoTitle";
            this.radioPhotoTitle.DrawIndicator = true;
            this.radioPhotoTitle.UseUnderline = true;
            this.radioPhotoTitle.Group = this.radioPhotoId.Group;
            this.hbox3.Add(this.radioPhotoTitle);
            var w17 = ((Box.BoxChild) (this.hbox3[this.radioPhotoTitle]));
            w17.Position = 1;
            this.vbox13.Add(this.hbox3);
            var w18 = ((Box.BoxChild) (this.vbox13[this.hbox3]));
            w18.Position = 0;
            // Container child vbox13.Gtk.Box+BoxChild
            this.hbox4 = new HBox();
            this.hbox4.Name = "hbox4";
            this.hbox4.Spacing = 6;
            // Container child hbox4.Gtk.Box+BoxChild
            this.entryDownloadLocation = new Entry();
            this.entryDownloadLocation.CanFocus = true;
            this.entryDownloadLocation.Name = "entryDownloadLocation";
            this.entryDownloadLocation.IsEditable = false;
            this.entryDownloadLocation.InvisibleChar = '●';
            this.hbox4.Add(this.entryDownloadLocation);
            var w19 = ((Box.BoxChild) (this.hbox4[this.entryDownloadLocation]));
            w19.Position = 0;
            // Container child hbox4.Gtk.Box+BoxChild
            this.buttonDownloadLocation = new Button();
            this.buttonDownloadLocation.WidthRequest = 0;
            this.buttonDownloadLocation.CanFocus = true;
            this.buttonDownloadLocation.Name = "buttonDownloadLocation";
            this.buttonDownloadLocation.UseUnderline = true;
            this.buttonDownloadLocation.Label = Catalog.GetString("...");
            this.hbox4.Add(this.buttonDownloadLocation);
            var w20 = ((Box.BoxChild) (this.hbox4[this.buttonDownloadLocation]));
            w20.Position = 1;
            w20.Expand = false;
            w20.Fill = false;
            this.vbox13.Add(this.hbox4);
            var w21 = ((Box.BoxChild) (this.vbox13[this.hbox4]));
            w21.Position = 1;
            w21.Fill = false;
            // Container child vbox13.Gtk.Box+BoxChild
            this.comboboxDownloadSize = ComboBox.NewText();
            this.comboboxDownloadSize.AppendText(Catalog.GetString("Medium"));
            this.comboboxDownloadSize.AppendText(Catalog.GetString("Large"));
            this.comboboxDownloadSize.AppendText(Catalog.GetString("Original"));
            this.comboboxDownloadSize.Name = "comboboxDownloadSize";
            this.vbox13.Add(this.comboboxDownloadSize);
            var w22 = ((Box.BoxChild) (this.vbox13[this.comboboxDownloadSize]));
            w22.Position = 2;
            w22.Fill = false;
            // Container child vbox13.Gtk.Box+BoxChild
            this.hbox8 = new HBox();
            this.hbox8.Name = "hbox8";
            this.hbox8.Homogeneous = true;
            this.hbox8.Spacing = 6;
            // Container child hbox8.Gtk.Box+BoxChild
            this.checkbuttonTags = new CheckButton();
            this.checkbuttonTags.CanFocus = true;
            this.checkbuttonTags.Name = "checkbuttonTags";
            this.checkbuttonTags.Label = Catalog.GetString("Tags");
            this.checkbuttonTags.DrawIndicator = true;
            this.checkbuttonTags.UseUnderline = true;
            this.hbox8.Add(this.checkbuttonTags);
            var w23 = ((Box.BoxChild) (this.hbox8[this.checkbuttonTags]));
            w23.Position = 0;
            // Container child hbox8.Gtk.Box+BoxChild
            this.checkbuttonDescription = new CheckButton();
            this.checkbuttonDescription.CanFocus = true;
            this.checkbuttonDescription.Name = "checkbuttonDescription";
            this.checkbuttonDescription.Label = Catalog.GetString("Description");
            this.checkbuttonDescription.DrawIndicator = true;
            this.checkbuttonDescription.UseUnderline = true;
            this.hbox8.Add(this.checkbuttonDescription);
            var w24 = ((Box.BoxChild) (this.hbox8[this.checkbuttonDescription]));
            w24.Position = 1;
            this.vbox13.Add(this.hbox8);
            var w25 = ((Box.BoxChild) (this.vbox13[this.hbox8]));
            w25.Position = 3;
            w25.Expand = false;
            // Container child vbox13.Gtk.Box+BoxChild
            this.hbox9 = new HBox();
            this.hbox9.Name = "hbox9";
            this.hbox9.Homogeneous = true;
            this.hbox9.Spacing = 6;
            // Container child hbox9.Gtk.Box+BoxChild
            this.checkbuttonTitle = new CheckButton();
            this.checkbuttonTitle.CanFocus = true;
            this.checkbuttonTitle.Name = "checkbuttonTitle";
            this.checkbuttonTitle.Label = Catalog.GetString("Title");
            this.checkbuttonTitle.DrawIndicator = true;
            this.checkbuttonTitle.UseUnderline = true;
            this.hbox9.Add(this.checkbuttonTitle);
            var w26 = ((Box.BoxChild) (this.hbox9[this.checkbuttonTitle]));
            w26.Position = 0;
            // Container child hbox9.Gtk.Box+BoxChild
            this.fixed5 = new Fixed();
            this.fixed5.Name = "fixed5";
            this.fixed5.HasWindow = false;
            this.hbox9.Add(this.fixed5);
            var w27 = ((Box.BoxChild) (this.hbox9[this.fixed5]));
            w27.Position = 1;
            this.vbox13.Add(this.hbox9);
            var w28 = ((Box.BoxChild) (this.vbox13[this.hbox9]));
            w28.Position = 4;
            w28.Expand = false;
            // Container child vbox13.Gtk.Box+BoxChild
            this.hbox7 = new HBox();
            this.hbox7.Name = "hbox7";
            this.hbox7.Spacing = 6;
            // Container child hbox7.Gtk.Box+BoxChild
            this.labelCacheSizeValue = new Label();
            this.labelCacheSizeValue.Name = "labelCacheSizeValue";
            this.labelCacheSizeValue.LabelProp = Catalog.GetString("0 KB");
            this.hbox7.Add(this.labelCacheSizeValue);
            var w29 = ((Box.BoxChild) (this.hbox7[this.labelCacheSizeValue]));
            w29.Position = 0;
            w29.Expand = false;
            w29.Fill = false;
            // Container child hbox7.Gtk.Box+BoxChild
            this.buttonEmptyCache = new Button();
            this.buttonEmptyCache.WidthRequest = 100;
            this.buttonEmptyCache.HeightRequest = 0;
            this.buttonEmptyCache.CanFocus = true;
            this.buttonEmptyCache.Name = "buttonEmptyCache";
            this.buttonEmptyCache.UseUnderline = true;
            this.buttonEmptyCache.Label = Catalog.GetString("Empty Cache");
            this.hbox7.Add(this.buttonEmptyCache);
            var w30 = ((Box.BoxChild) (this.hbox7[this.buttonEmptyCache]));
            w30.Position = 1;
            w30.Expand = false;
            w30.Fill = false;
            w30.Padding = 5;
            this.vbox13.Add(this.hbox7);
            var w31 = ((Box.BoxChild) (this.vbox13[this.hbox7]));
            w31.PackType = ((PackType) (1));
            w31.Position = 5;
            w31.Expand = false;
            w31.Fill = false;
            // Container child vbox13.Gtk.Box+BoxChild
            this.hbox5 = new HBox();
            this.hbox5.Name = "hbox5";
            this.hbox5.Spacing = 6;
            // Container child hbox5.Gtk.Box+BoxChild
            this.entryCacheLocation = new Entry();
            this.entryCacheLocation.CanFocus = true;
            this.entryCacheLocation.Name = "entryCacheLocation";
            this.entryCacheLocation.IsEditable = false;
            this.entryCacheLocation.InvisibleChar = '●';
            this.hbox5.Add(this.entryCacheLocation);
            var w32 = ((Box.BoxChild) (this.hbox5[this.entryCacheLocation]));
            w32.Position = 0;
            // Container child hbox5.Gtk.Box+BoxChild
            this.buttonCacheLocation = new Button();
            this.buttonCacheLocation.CanFocus = true;
            this.buttonCacheLocation.Name = "buttonCacheLocation";
            this.buttonCacheLocation.UseUnderline = true;
            this.buttonCacheLocation.Label = Catalog.GetString("...");
            this.hbox5.Add(this.buttonCacheLocation);
            var w33 = ((Box.BoxChild) (this.hbox5[this.buttonCacheLocation]));
            w33.Position = 1;
            w33.Expand = false;
            w33.Fill = false;
            this.vbox13.Add(this.hbox5);
            var w34 = ((Box.BoxChild) (this.vbox13[this.hbox5]));
            w34.PackType = ((PackType) (1));
            w34.Position = 6;
            w34.Expand = false;
            w34.Fill = false;
            // Container child vbox13.Gtk.Box+BoxChild
            this.hbox6 = new HBox();
            this.hbox6.Name = "hbox6";
            this.hbox6.Homogeneous = true;
            this.hbox6.Spacing = 6;
            // Container child hbox6.Gtk.Box+BoxChild
            this.radioTagsInternal = new RadioButton(Catalog.GetString("Internal"));
            this.radioTagsInternal.CanFocus = true;
            this.radioTagsInternal.Name = "radioTagsInternal";
            this.radioTagsInternal.DrawIndicator = true;
            this.radioTagsInternal.UseUnderline = true;
            this.radioTagsInternal.Group = new SList(IntPtr.Zero);
            this.hbox6.Add(this.radioTagsInternal);
            var w35 = ((Box.BoxChild) (this.hbox6[this.radioTagsInternal]));
            w35.Position = 0;
            // Container child hbox6.Gtk.Box+BoxChild
            this.radioTagsOriginal = new RadioButton(Catalog.GetString("Original (Slower download)"));
            this.radioTagsOriginal.CanFocus = true;
            this.radioTagsOriginal.Name = "radioTagsOriginal";
            this.radioTagsOriginal.DrawIndicator = true;
            this.radioTagsOriginal.UseUnderline = true;
            this.radioTagsOriginal.Group = this.radioTagsInternal.Group;
            this.hbox6.Add(this.radioTagsOriginal);
            var w36 = ((Box.BoxChild) (this.hbox6[this.radioTagsOriginal]));
            w36.Position = 1;
            this.vbox13.Add(this.hbox6);
            var w37 = ((Box.BoxChild) (this.vbox13[this.hbox6]));
            w37.PackType = ((PackType) (1));
            w37.Position = 7;
            w37.Expand = false;
            // Container child vbox13.Gtk.Box+BoxChild
            this.comboboxSafetyLevel = ComboBox.NewText();
            this.comboboxSafetyLevel.AppendText(Catalog.GetString("Safe"));
            this.comboboxSafetyLevel.AppendText(Catalog.GetString("Moderate"));
            this.comboboxSafetyLevel.AppendText(Catalog.GetString("Restricted"));
            this.comboboxSafetyLevel.Name = "comboboxSafetyLevel";
            this.vbox13.Add(this.comboboxSafetyLevel);
            var w38 = ((Box.BoxChild) (this.vbox13[this.comboboxSafetyLevel]));
            w38.PackType = ((PackType) (1));
            w38.Position = 8;
            w38.Expand = false;
            w38.Fill = false;
            // Container child vbox13.Gtk.Box+BoxChild
            this.comboboxPhotosPerPage = ComboBox.NewText();
            this.comboboxPhotosPerPage.AppendText(Catalog.GetString("25"));
            this.comboboxPhotosPerPage.AppendText(Catalog.GetString("50"));
            this.comboboxPhotosPerPage.AppendText(Catalog.GetString("75"));
            this.comboboxPhotosPerPage.AppendText(Catalog.GetString("100"));
            this.comboboxPhotosPerPage.Name = "comboboxPhotosPerPage";
            this.vbox13.Add(this.comboboxPhotosPerPage);
            var w39 = ((Box.BoxChild) (this.vbox13[this.comboboxPhotosPerPage]));
            w39.PackType = ((PackType) (1));
            w39.Position = 9;
            w39.Expand = false;
            w39.Fill = false;
            this.hbox1.Add(this.vbox13);
            var w40 = ((Box.BoxChild) (this.hbox1[this.vbox13]));
            w40.Position = 2;
            w40.Expand = false;
            w40.Fill = false;
            w40.Padding = 10;
            // Container child hbox1.Gtk.Box+BoxChild
            this.alignment3 = new Alignment(0.5F, 0.5F, 1F, 1F);
            this.alignment3.Name = "alignment3";
            this.hbox1.Add(this.alignment3);
            var w41 = ((Box.BoxChild) (this.hbox1[this.alignment3]));
            w41.PackType = ((PackType) (1));
            w41.Position = 3;
            this.vbox9.Add(this.hbox1);
            var w42 = ((Box.BoxChild) (this.vbox9[this.hbox1]));
            w42.Position = 2;
            w42.Padding = 10;
            // Container child vbox9.Gtk.Box+BoxChild
            this.hbox2 = new HBox();
            this.hbox2.Name = "hbox2";
            this.hbox2.Homogeneous = true;
            this.hbox2.Spacing = 6;
            // Container child hbox2.Gtk.Box+BoxChild
            this.buttonCancel = new Button();
            this.buttonCancel.WidthRequest = 80;
            this.buttonCancel.CanFocus = true;
            this.buttonCancel.Name = "buttonCancel";
            this.buttonCancel.UseUnderline = true;
            this.buttonCancel.Label = Catalog.GetString("Cancel");
            this.hbox2.Add(this.buttonCancel);
            var w43 = ((Box.BoxChild) (this.hbox2[this.buttonCancel]));
            w43.Position = 0;
            w43.Expand = false;
            w43.Fill = false;
            // Container child hbox2.Gtk.Box+BoxChild
            this.buttonDefaults = new Button();
            this.buttonDefaults.WidthRequest = 80;
            this.buttonDefaults.CanFocus = true;
            this.buttonDefaults.Name = "buttonDefaults";
            this.buttonDefaults.UseUnderline = true;
            this.buttonDefaults.Label = Catalog.GetString("Defaults");
            this.hbox2.Add(this.buttonDefaults);
            var w44 = ((Box.BoxChild) (this.hbox2[this.buttonDefaults]));
            w44.Position = 1;
            w44.Expand = false;
            w44.Fill = false;
            // Container child hbox2.Gtk.Box+BoxChild
            this.buttonSave = new Button();
            this.buttonSave.WidthRequest = 80;
            this.buttonSave.CanFocus = true;
            this.buttonSave.Name = "buttonSave";
            this.buttonSave.UseUnderline = true;
            this.buttonSave.Label = Catalog.GetString("Save");
            this.hbox2.Add(this.buttonSave);
            var w45 = ((Box.BoxChild) (this.hbox2[this.buttonSave]));
            w45.Position = 2;
            w45.Expand = false;
            w45.Fill = false;
            this.vbox9.Add(this.hbox2);
            var w46 = ((Box.BoxChild) (this.vbox9[this.hbox2]));
            w46.Position = 3;
            w46.Expand = false;
            w46.Fill = false;
            w46.Padding = 5;
            Add(this.vbox9);
            if ((Child != null)) {
                Child.ShowAll();
            }
            DefaultWidth = 612;
            DefaultHeight = 534;
            Show();
            DeleteEvent += OnDeleteEvent;
            this.buttonDownloadLocation.Clicked += buttonDownloadLocationClick;
            this.buttonCacheLocation.Clicked += buttonCacheLocationClick;
            this.buttonEmptyCache.Clicked += buttonEmptyCacheClick;
            this.buttonCancel.Clicked += buttonCancelClick;
            this.buttonDefaults.Clicked += buttonDefaultsClick;
            this.buttonSave.Clicked += buttonSaveClick;
        }
    }
}
