
// This file has been generated by the GUI designer. Do not modify.
namespace FloydPink.Flickr.Downloadr.UI.Widgets
{
	public partial class GridWidget
	{
		private global::Gtk.VBox vboxContainer;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget FloydPink.Flickr.Downloadr.UI.Widgets.GridWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "FloydPink.Flickr.Downloadr.UI.Widgets.GridWidget";
			// Container child FloydPink.Flickr.Downloadr.UI.Widgets.GridWidget.Gtk.Container+ContainerChild
			this.vboxContainer = new global::Gtk.VBox ();
			this.vboxContainer.Name = "vboxContainer";
			this.vboxContainer.Homogeneous = true;
			this.vboxContainer.Spacing = 6;
			this.Add (this.vboxContainer);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
