using System;
using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyTitleAttribute("flickrDownloadr")]
[assembly: AssemblyDescriptionAttribute("A cross-platform desktop app, written in Mono that would download (all or selecte" +
    "d) photos from your photostream in their selected size along with their descript" +
    "ion, title and tags.")]
[assembly: AssemblyConfigurationAttribute("Release")]
[assembly: AssemblyCompanyAttribute("http://flickrdownloadr.com")]
[assembly: AssemblyProductAttribute("flickr downloadr")]
[assembly: AssemblyCopyrightAttribute("Copyright © 2012-2021 flickr downloadr")]
[assembly: AssemblyTrademarkAttribute("")]
[assembly: AssemblyCultureAttribute("")]
[assembly: AssemblyVersionAttribute("3.3.4.1")]
[assembly: AssemblyFileVersionAttribute("3.3.4.1")]

